spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_DATABASE_URL}
    username: ${RDS_DATABASE_USERNAME}
    password: ${RDS_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: laf-s3-bucket
      folder: prod/images/
    stack:
      auto: false

websocket:
  url: wanna-find.com